# numpy - Quick Tutorial

### numpy methods and variables

In [7]:
import numpy

d = [i for i in dir(numpy) 
     if not i.startswith('_')]
print('These are Variables of numpy module:')
print('*'*37)
for x in d:
    if not callable(getattr(numpy, x)):
        print(x)
else:
    print()

print('These are Classes and Methods of numpy module:')
print('*'*47)
for x in d:
    if callable(getattr(numpy, x)):
        print(x)

These are Variables of numpy module:
*************************************
ALLOW_THREADS
BUFSIZE
CLIP
ERR_CALL
ERR_DEFAULT
ERR_IGNORE
ERR_LOG
ERR_PRINT
ERR_RAISE
ERR_WARN
FLOATING_POINT_SUPPORT
FPE_DIVIDEBYZERO
FPE_INVALID
FPE_OVERFLOW
FPE_UNDERFLOW
False_
Inf
Infinity
MAXDIMS
MAY_SHARE_BOUNDS
MAY_SHARE_EXACT
NAN
NINF
NZERO
NaN
PINF
PZERO
RAISE
SHIFT_DIVIDEBYZERO
SHIFT_INVALID
SHIFT_OVERFLOW
SHIFT_UNDERFLOW
ScalarType
True_
UFUNC_BUFSIZE_DEFAULT
UFUNC_PYVALS_NAME
WRAP
absolute_import
c_
cast
char
compat
core
ctypeslib
division
e
emath
euler_gamma
fft
index_exp
inf
infty
lib
linalg
little_endian
ma
math
matrixlib
mgrid
nan
nbytes
newaxis
numarray
ogrid
oldnumeric
pi
polynomial
print_function
r_
random
rec
s_
sctypeDict
sctypeNA
sctypes
sys
testing
tracemalloc_domain
typeDict
typeNA
typecodes
version
warnings

These are Classes and Methods of numpy module:
***********************************************
AxisError
ComplexWarning
DataSource
MachAr
ModuleDeprecationWarning
RankWarning
Teste

### list atrributes

In [6]:
import numpy 

dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '_distributor_init',


### The Basics

### An example

#### Creation numpy array

In [10]:
import numpy as np

a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### Dmensions of the array. 

In [11]:
a.shape

(3, 5)

#### Number of axes (dimensions) of the array.

In [12]:
a.ndim

2

#### Array of elements of type

In [13]:
a.dtype.name

'int32'

#### Size in bytes of each element of the array

In [15]:
a.itemsize

4

#### Total number of elements of the array

In [14]:
a.size

15

In [16]:
type(a)

numpy.ndarray

#### Create array directly

In [18]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

### Array Creation

In [12]:
import numpy as np

a = np.array([1,2,3])
print(a)
print(a.dtype)

[1 2 3]
int32


###  Frequent error

In [ ]:
a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT

### array transforms

In [16]:
import numpy as np

a = np.array([(1,2,3),(4,4.1,5)])
a

array([[1. , 2. , 3. ],
       [4. , 4.1, 5. ]])

### Decalre type at array creation time

In [18]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]], dtype = complex)
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

### zeros,ones,empty array creation

In [20]:
import numpy as np

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
import numpy as np
a = np.zeros([1, 2]+[3], dtype = int)
a

array([[[0, 0, 0],
        [0, 0, 0]]])

In [27]:
import numpy as np

np.ones((2,3), dtype = np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [14]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [28]:
import numpy as np

np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Create an empty NumPy array

In [64]:
import numpy
numpy.array([])

array([], dtype=float64)

In [66]:
numpy.empty((0,0))

array([], shape=(0, 0), dtype=float64)

### To create sequences of numbers

In [17]:
import numpy as np
a = np.arange(3)
a

array([0, 1, 2])

In [18]:
import numpy as np
a = np.arange(3)**3
a

array([0, 1, 8], dtype=int32)

In [29]:
import numpy as np

np.arange(10,20,3)

array([10, 13, 16, 19])

In [30]:
np.arange( 0, 2, 0.3 ) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [100]:
a = np.arange(12)
a.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
from numpy import pi

np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [50]:
x = np.linspace( 0, 2*pi, 9 )  
x

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
       3.92699082, 4.71238898, 5.49778714, 6.28318531])

In [49]:
x = np.linspace( 0, 2*pi, 9 )  
np.sin(x)

array([ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,  7.07106781e-01,
        1.22464680e-16, -7.07106781e-01, -1.00000000e+00, -7.07106781e-01,
       -2.44929360e-16])

### Create random number array 

In [81]:
np.random.random(2)

array([0.04474747, 0.79195547])

In [13]:
np.random.random((2,3))

array([[0.15175525, 0.44046411, 0.59495662],
       [0.36199837, 0.3996995 , 0.77658811]])

In [86]:
import numpy as np

a = np.random.randint((10), size=10)

array([6, 5, 6, 9, 2, 6, 5, 3, 8, 4])

In [8]:
import numpy as np

np.floor(np.random.random((3,4)))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
import numpy as np

np.floor(10*np.random.random((3,4)))

array([[8., 8., 5., 1.],
       [7., 2., 1., 3.],
       [9., 8., 5., 5.]])

### Create array from function

In [32]:
def f(x,y):
    return x

b = np.fromfunction(f,(3,4),dtype=int)
b

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [33]:
def f(x,y):
    return y

b = np.fromfunction(f,(3,4),dtype=int)
b

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [30]:
def f(x,y):
    return x+y

b = np.fromfunction(f,(3,4),dtype=int)
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

### Printing Arrays

#### Print one diemensional array

In [64]:
import numpy as np

a = np.arange(5)
print(a)

[0 1 2 3 4]


#### Print two diemensional array


In [65]:
import numpy as np

a = np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### 3D array

In [66]:
a = np.arange(24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


#### Reshape array if array too large.
If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.

In [67]:
a = np.arange(10000)
print(a)

[   0    1    2 ... 9997 9998 9999]


In [71]:
a = np.arange(10000).reshape(100, 100)
print(a)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


#### To disable this behaviou

In [ ]:
np.set_printoptions(threshold=np.nan)

### Basic Operations

In [98]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


#### Add

In [93]:
c = a+b
print(c)

[20 31 42 53]


#### Substract

In [94]:
d = a-b
print(d)

[20 29 38 47]


#### Multipy

In [95]:
m = b**2
print(m)

[0 1 4 9]


#### Multiply with function

In [101]:
10*np.sin(b)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

#### Comparsion

In [102]:
a < 35

array([ True,  True, False, False])

### matrix *,@,.
Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. 

The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

#### elementwise product

In [4]:
import numpy as np

A = np.array([[1, 1],
             [0, 1]])
B = np. array([[2, 0],
              [3, 4]])
A*B

array([[2, 0],
       [0, 4]])

#### matrix product

In [5]:
A@B

array([[5, 4],
       [3, 4]])

In [7]:
A.dot(B)

array([[5, 4],
       [3, 4]])

#### += and *=
Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [22]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[0.61447353 0.64695759 0.95476637]
 [0.18954846 0.01209349 0.8623224 ]]


In [27]:
a *= 3
a

array([[27, 27, 27],
       [27, 27, 27]])

In [29]:
b += a
b

array([[54.61447353, 54.64695759, 54.95476637],
       [54.18954846, 54.01209349, 54.8623224 ]])

In [31]:
# b is not automatically converted to integer type
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

####  Operating with arrays of different types
When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [36]:
a = np.ones(3)
a

array([1., 1., 1.])

In [35]:
a = np.ones(3, dtype=np.int32)
a

array([1, 1, 1])

In [40]:
b = np.linspace(0,np.pi,3)
b

array([0.        , 1.57079633, 3.14159265])

In [42]:
b.dtype.name

'float64'

In [45]:
c = a + b
print(c)
c.dtype.name

[1.         2.57079633 4.14159265]


'float64'

In [46]:
d = np.exp(c*1j)
print(d)
d.dtype.name

[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]


'complex128'

### sum,min,max

In [48]:
a = np.random.random((2,3))
a

array([[0.08019903, 0.03886113, 0.71527157],
       [0.62177326, 0.63443245, 0.56160152]])

In [49]:
sum(a)

array([0.70197229, 0.67329358, 1.27687309])

In [50]:
a.sum()

2.6521389595745504

In [51]:
a.min()

0.038861129794161675

In [52]:
a.max()

0.7152715660985868

#### axis operations

In [53]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
b.sum(axis=0) ##Column

array([12, 15, 18, 21])

In [59]:
b.sum(axis=1)  ##Row

array([ 6, 22, 38])

In [61]:
b.min(axis=0)

array([0, 1, 2, 3])

In [62]:
b.min(axis=1)

array([0, 4, 8])

#### cumulative sum along each row

In [5]:
import numpy as np

b = np.arange(12).reshape(3,4)
print(b)
b.cumsum(axis=1)   

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

### Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). 

Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [6]:
import numpy as np

B = np.arange(3)
B

array([0, 1, 2])

In [7]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

#### What exactly does numpy.exp() do?

In [8]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [9]:
np.sqrt(196)

14.0

In [12]:
C = np.array([2., -1., 4.])

In [14]:
print(B)
print(C)

np.add(B,C)

[0 1 2]
[ 2. -1.  4.]


array([2., 0., 6.])

### Indexing, Slicing and Iterating

In [3]:
import numpy as np

a = np.arange(10)*2
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
a[3]

6

In [5]:
a[1:4]

array([2, 4, 6])

In [6]:
a[:5:2] = 1000
a

array([1000,    2, 1000,    6, 1000,   10,   12,   14,   16,   18])

In [7]:
a[::-1]

array([  18,   16,   14,   12,   10, 1000,    6, 1000,    2, 1000])

### Multidimensional index and slicing

In [34]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

#### Second array and third element

In [35]:
b[2,3]

23

#### from 1st array to 4th array and 2nd element

In [36]:
b[1:4,2]

array([12, 22, 32])

#### All array and 1st element

In [37]:
b[:,1]

array([ 1, 11, 21, 31, 41])

#### from 1st to 3rd array and all elements

In [38]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

#### last array only

In [39]:
b[-1]

array([40, 41, 42, 43])

#### dots

In [40]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])

In [41]:
c.shape

(2, 2, 3)

#### first stack and all array and all elements

In [43]:
c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

#### All stack and all array and 2nd elements

In [45]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

### Iterating

In [46]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [47]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


#### How to merge all array?

In [51]:
print(*b.flat)

0 1 2 3 10 11 12 13 20 21 22 23 30 31 32 33 40 41 42 43


In [52]:
for i in b.flat:
    print(i)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


###  Shape Manipulation

#### Changing the shape of an array

In [11]:
import numpy as np

a = np.floor(10*np.random.random((3,4)))
a

array([[7., 4., 3., 8.],
       [7., 5., 2., 0.],
       [9., 8., 4., 3.]])

In [12]:
a.shape

(3, 4)

In [15]:
a.ravel()    # returns the array, flattened

array([7., 4., 3., 8., 7., 5., 2., 0., 9., 8., 4., 3.])

#### reshape()

In [16]:
a

array([[7., 4., 3., 8.],
       [7., 5., 2., 0.],
       [9., 8., 4., 3.]])

In [17]:
a.reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [18]:
a.shape

(3, 4)

In [19]:
a.reshape(2,6)

array([[7., 4., 3., 8., 7., 5.],
       [2., 0., 9., 8., 4., 3.]])

In [20]:
a.reshape(6,2)

array([[7., 4.],
       [3., 8.],
       [7., 5.],
       [2., 0.],
       [9., 8.],
       [4., 3.]])

In [21]:
a

array([[7., 4., 3., 8.],
       [7., 5., 2., 0.],
       [9., 8., 4., 3.]])

#### transpos

In [22]:
a

array([[7., 4., 3., 8.],
       [7., 5., 2., 0.],
       [9., 8., 4., 3.]])

In [24]:
a.shape

(3, 4)

In [25]:
a.T     # returns the array, transposed

array([[7., 7., 9.],
       [4., 5., 8.],
       [3., 2., 4.],
       [8., 0., 3.]])

In [26]:
a.T.shape

(4, 3)

#### resize
It is resize original array.

In [38]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a.resize((2,6))

In [43]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

#### flaten array

In [31]:
import numpy as np

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a.shape

(3, 4)

In [32]:
print(*a.flat)

0 1 2 3 4 5 6 7 8 9 10 11


In [34]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
a.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [46]:
a.resize((1,12))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

### Stacking together different arrays or Merge single Array

In [53]:
import numpy as np

a = np.floor(10*np.random.random((2,2)))
a

array([[1., 7.],
       [8., 5.]])

In [58]:
import numpy as np

b = np.floor(10*np.random.random((2,2)))
b

array([[6., 7.],
       [6., 4.]])

In [59]:
np.vstack((a,b))

array([[1., 7.],
       [8., 5.],
       [6., 7.],
       [6., 4.]])

In [60]:
np.hstack((a,b))

array([[1., 7., 6., 7.],
       [8., 5., 6., 4.]])

In [62]:
from numpy import newaxis

np.column_stack((a,b)) 

array([[1., 7., 6., 7.],
       [8., 5., 6., 4.]])

In [64]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b))     # returns a 2D array


array([[4., 3.],
       [2., 8.]])

In [66]:
np.hstack((a,b))    # the result is different

array([4., 2., 3., 8.])

#### newaxis

In [67]:
a

array([4., 2.])

In [70]:
np.vstack(a)

array([[4.],
       [2.]])

In [72]:
a[:,newaxis]    # this allows to have a 2D columns vector

array([[4.],
       [2.]])

#### Inter change elements

In [73]:
a

array([4., 2.])

In [74]:
b

array([3., 8.])

In [77]:
np.column_stack((a[:,newaxis], b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [78]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

array([[4., 3.],
       [2., 8.]])

In [80]:
np.r_[2:4,0,4]

array([2, 3, 0, 4])

### Splitting one array into several smaller ones

In [94]:
a = np.floor(10*np.random.random((2,9)))
a

array([[8., 6., 4., 3., 1., 4., 9., 7., 8.],
       [2., 0., 7., 1., 3., 9., 7., 0., 3.]])

In [95]:
np.hsplit(a, 3)

[array([[8., 6., 4.],
        [2., 0., 7.]]), array([[3., 1., 4.],
        [1., 3., 9.]]), array([[9., 7., 8.],
        [7., 0., 3.]])]

In [97]:
np.hsplit(a,(3,4))  # Split a after the third and the fourth column

[array([[8., 6., 4.],
        [2., 0., 7.]]), array([[3.],
        [1.]]), array([[1., 4., 9., 7., 8.],
        [3., 9., 7., 0., 3.]])]

## Excercise

### How to convert array to numpy array conversion?


In [118]:
from pathlib import Path
import numpy as np

p = Path('/etc/hosts').read_text().splitlines()
host = [i.split() for i in p if not i.startswith('#')]
length = max(map(len, host))
y=numpy.array([x+[None]*(length-len(x)) for x in host])
ip = y[:,:1]
hostname = y[:,1:2]
print(ip)
print(hostname)

[['127.0.0.1']
 ['127.0.1.1']
 [None]
 ['::1']
 ['fe00::0']
 ['ff00::0']
 ['ff02::1']
 ['ff02::2']]
[['localhost']
 ['joe']
 [None]
 ['ip6-localhost']
 ['ip6-localnet']
 ['ip6-mcastprefix']
 ['ip6-allnodes']
 ['ip6-allrouters']]


### Extracting first n columns of a numpy matrix

In [96]:
import numpy as np
arry = np.array([[-0.57098887, -0.4274751 , -0.38459931, -0.58593526],
         [-0.22279713, -0.51723555,  0.82462029,  0.05319973],
         [ 0.67492385, -0.69294472, -0.2531966 ,  0.01403201],
         [ 0.41086611,  0.26374238,  0.32859738, -0.80848795]])

#Fetch 1st 2 columns
arry[:,:2]

#you want to extract the first 2 rows and first 3 columns
arry[0:2,0:3]

array([[-0.57098887, -0.4274751 , -0.38459931],
       [-0.22279713, -0.51723555,  0.82462029]])

### List of lists into numpy array
If your list of lists contains lists with varying number of elements then the answer of Ignacio Vazquez-Abrams will not work. Instead there are 3 options:


#### 1) Make an array of arrays:

In [106]:
x=[[1,2],[1,2,3],[1]]
y=numpy.array([numpy.array(xi) for xi in x])
print(type(y))
y

<class 'numpy.ndarray'>


array([array([1, 2]), array([1, 2, 3]), array([1])], dtype=object)

#### 2) Make an array of lists:

In [109]:
x=[[1,2],[1,2,3],[1]]
y=numpy.array(x)
print(type(y))
y

<class 'numpy.ndarray'>


array([list([1, 2]), list([1, 2, 3]), list([1])], dtype=object)

#### First make the lists equal in length:

In [110]:
x=[[1,2],[1,2,3],[1]]
length = max(map(len, x))
y=numpy.array([xi+[None]*(length-len(xi)) for xi in x])
y

array([[1, 2, None],
       [1, 2, 3],
       [1, None, None]], dtype=object)

### How to convert this array into 0 and 1 in python? 

In [20]:
import numpy as np

a = np.array([[False, False, True],

[False, False, True],

[False, False, True],

[False, False, True],

[ True, False, False],

[ True, False, False],

[False, True, False]], dtype = int)

a

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])