# NumPy - Quick Tutorial

### numpy methods and variables

In [7]:
import numpy

d = [i for i in dir(numpy) 
     if not i.startswith('_')]
print('These are Variables of numpy module:')
print('*'*37)
for x in d:
    if not callable(getattr(numpy, x)):
        print(x)
else:
    print()

print('These are Classes and Methods of numpy module:')
print('*'*47)
for x in d:
    if callable(getattr(numpy, x)):
        print(x)

These are Variables of numpy module:
*************************************
ALLOW_THREADS
BUFSIZE
CLIP
ERR_CALL
ERR_DEFAULT
ERR_IGNORE
ERR_LOG
ERR_PRINT
ERR_RAISE
ERR_WARN
FLOATING_POINT_SUPPORT
FPE_DIVIDEBYZERO
FPE_INVALID
FPE_OVERFLOW
FPE_UNDERFLOW
False_
Inf
Infinity
MAXDIMS
MAY_SHARE_BOUNDS
MAY_SHARE_EXACT
NAN
NINF
NZERO
NaN
PINF
PZERO
RAISE
SHIFT_DIVIDEBYZERO
SHIFT_INVALID
SHIFT_OVERFLOW
SHIFT_UNDERFLOW
ScalarType
True_
UFUNC_BUFSIZE_DEFAULT
UFUNC_PYVALS_NAME
WRAP
absolute_import
c_
cast
char
compat
core
ctypeslib
division
e
emath
euler_gamma
fft
index_exp
inf
infty
lib
linalg
little_endian
ma
math
matrixlib
mgrid
nan
nbytes
newaxis
numarray
ogrid
oldnumeric
pi
polynomial
print_function
r_
random
rec
s_
sctypeDict
sctypeNA
sctypes
sys
testing
tracemalloc_domain
typeDict
typeNA
typecodes
version
warnings

These are Classes and Methods of numpy module:
***********************************************
AxisError
ComplexWarning
DataSource
MachAr
ModuleDeprecationWarning
RankWarning
Teste

### list atrributes

In [6]:
import numpy 

dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '_distributor_init',


### The Basics

### An example

#### Creation numpy array

In [10]:
import numpy as np

a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### Dmensions of the array. 

In [11]:
a.shape

(3, 5)

#### Number of axes (dimensions) of the array.

In [12]:
a.ndim

2

#### Array of elements of type

In [13]:
a.dtype.name

'int32'

#### Size in bytes of each element of the array

In [15]:
a.itemsize

4

#### Total number of elements of the array

In [14]:
a.size

15

In [16]:
type(a)

numpy.ndarray

#### Create array directly

In [18]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

### Array Creation

In [12]:
import numpy as np

a = np.array([1,2,3])
print(a)
print(a.dtype)

[1 2 3]
int32


###  Frequent error

In [ ]:
a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT

### array transforms

In [16]:
import numpy as np

a = np.array([(1,2,3),(4,4.1,5)])
a

array([[1. , 2. , 3. ],
       [4. , 4.1, 5. ]])

### Decalre type at array creation time

In [18]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]], dtype = complex)
a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

### zeros,ones,empty array creation

In [20]:
import numpy as np

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
import numpy as np

np.ones((2,3), dtype = np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [28]:
import numpy as np

np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### To create sequences of numbers

In [29]:
import numpy as np

np.arange(10,20,3)

array([10, 13, 16, 19])

In [30]:
np.arange( 0, 2, 0.3 ) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

### What is pi?

In [42]:
22/7

3.142857142857143

In [39]:
from numpy import pi

np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [50]:
x = np.linspace( 0, 2*pi, 9 )  
x

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
       3.92699082, 4.71238898, 5.49778714, 6.28318531])

In [49]:
x = np.linspace( 0, 2*pi, 9 )  
np.sin(x)

array([ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,  7.07106781e-01,
        1.22464680e-16, -7.07106781e-01, -1.00000000e+00, -7.07106781e-01,
       -2.44929360e-16])

### Printing Arrays

#### Print one diemensional array

In [64]:
import numpy as np

a = np.arange(5)
print(a)

[0 1 2 3 4]


#### Print two diemensional array


In [65]:
import numpy as np

a = np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### 3D array

In [66]:
a = np.arange(24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


#### Reshape array if array too large.
If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.

In [67]:
a = np.arange(10000)
print(a)

[   0    1    2 ... 9997 9998 9999]


In [71]:
a = np.arange(10000).reshape(100, 100)
print(a)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


#### To disable this behaviou

In [ ]:
np.set_printoptions(threshold=np.nan)

### Basic Operations

In [98]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


#### Add

In [93]:
c = a+b
print(c)

[20 31 42 53]


#### Substract

In [94]:
d = a-b
print(d)

[20 29 38 47]


#### Multipy

In [95]:
m = b**2
print(m)

[0 1 4 9]


#### Multiply with function

In [101]:
10*np.sin(b)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

#### Comparsion

In [102]:
a < 35

array([ True,  True, False, False])